server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_rest_api_qa?serverTimezone=America/Lima
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # Valida el esquema contra las entidades, no lo modifica

logging:
  level:
    root: INFO
    dev.magadiflo.app: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: INFO
    org.springframework.transaction: INFO
    org.springframework.data.jpa: INFO
